# Generated by Django 5.1.7 on 2025-03-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_rename_name_books_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Books",
        ),
    ]
