# Generated by Django 5.1.7 on 2025-03-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_initial"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="books",
            table_comment="Kitoblar-javoni",
        ),
    ]
