# Generated by Django 5.1.7 on 2025-03-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_books_table_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="books",
            options={"ordering": ["-updated_at"], "verbose_name": "Kitoblar"},
        ),
    ]
