# Generated by Django 5.1.7 on 2025-03-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_books_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="books",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Kitoblar",
                "verbose_name_plural": "Kitob",
            },
        ),
    ]
